// Knowledge graph data – all nodes and edges for the ToolTrack system
// Senast uppdaterad: 2026-06-11

export const LAST_UPDATED = '2026-06-11';

export const CATEGORIES = {
  workflow: { label: 'Arbetsflöde', color: '#8B1E1E', bg: '#8B1E1E15' },
  entity: { label: 'Entitet', color: '#2563eb', bg: '#2563eb15' },
  function: { label: 'Backend-funktion', color: '#7c3aed', bg: '#7c3aed15' },
  role: { label: 'Roll', color: '#0891b2', bg: '#0891b215' },
  email: { label: 'Email-notis', color: '#d97706', bg: '#d9770615' },
  page: { label: 'Sida i appen', color: '#16a34a', bg: '#16a34a15' },
};

export const NODES = [
  // === WORKFLOWS ===
  { id: 'wf_loan', label: 'Lånflöde', cat: 'workflow', desc: 'Komplett flöde för lån av maskiner: begäran → godkännande → lån → retur → bekräftelse.' },
  { id: 'wf_workwear', label: 'Arbetskläder-flöde', cat: 'workflow', desc: 'Begäran om arbetskläder/skyddsutrustning → godkännande → scanning → utlämning.' },
  { id: 'wf_lokalvard', label: 'Lokalvårdsartiklar-flöde', cat: 'workflow', desc: 'Begäran om lokalvårdsartiklar → godkännande → uttag → fakturering per kund.' },
  { id: 'wf_inventering', label: 'Inventeringsflöde', cat: 'workflow', desc: 'Inventering av maskiner/handredskap: starta session → skanna → sammanfatta → korrigera lager.' },
  { id: 'wf_import', label: 'Importflöde', cat: 'workflow', desc: 'Import av inköp, uttag och maskiner via Excel/CSV-filer.' },

  // === ENTITIES ===
  { id: 'e_loanrequest', label: 'LoanRequest', cat: 'entity', desc: 'Låneförfrågan med status: pending → approved → pending_return → returned.' },
  { id: 'e_tool', label: 'Tool', cat: 'entity', desc: 'Maskiner och redskap med status, plats, streckkod och avskrivning.' },
  { id: 'e_handtool', label: 'HandTool', cat: 'entity', desc: 'Handredskap med plats, status och streckkod.' },
  { id: 'e_workwearrequest', label: 'WorkwearRequest', cat: 'entity', desc: 'Begäran om arbetskläder, status: pending → approved → completed.' },
  { id: 'e_arbetsklader', label: 'ArbetskläderUtrustning', cat: 'entity', desc: 'Lager av arbetskläder och skyddsutrustning med storlek, streckkod, plats.' },
  { id: 'e_lokalvardrequest', label: 'LokalvardArtikelRequest', cat: 'entity', desc: 'Begäran om uttag av lokalvårdsartiklar.' },
  { id: 'e_lokalvardsartikel', label: 'LokalvardsArtikel', cat: 'entity', desc: 'Artiklar i lokalvårdslager med pris, streckkod, tröskelvärde, utgående-status.' },
  { id: 'e_uttag', label: 'Uttag', cat: 'entity', desc: 'Registrerade uttag av lokalvårdsartiklar med kostnad per kund/månad.' },
  { id: 'e_checkout', label: 'LokalvardCheckout', cat: 'entity', desc: 'Utlämningspost kopplad till godkänd begäran (arbetskläder).' },
  { id: 'e_inkop', label: 'LokalvardInköp', cat: 'entity', desc: 'Inköpsposter för lokalvårdsartiklar med datum, antal, pris och ordernummer.' },
  { id: 'e_location', label: 'Location', cat: 'entity', desc: 'Platser (arbetsplats, lager, fordon) med ansvarig person.' },
  { id: 'e_teammember', label: 'TeamMember', cat: 'entity', desc: 'Personal i systemet med roll, plats, emailprenumeration.' },
  { id: 'e_kund', label: 'Kund', cat: 'entity', desc: 'Kunder (Cemi, PHM, BRF, m.fl.) med projektnummer och status.' },
  { id: 'e_toollog', label: 'ToolLog', cat: 'entity', desc: 'Historiklogg för alla ändringar på maskiner.' },
  { id: 'e_servicerecord', label: 'ServiceRecord', cat: 'entity', desc: 'Servicelogg för maskiner och utrustning.' },
  { id: 'e_servicetemplate', label: 'ServiceTemplate', cat: 'entity', desc: 'Mallar för återkommande serviceåtgärder.' },
  { id: 'e_huvudmaskin', label: 'Huvudmaskin', cat: 'entity', desc: 'Traktorer, lastbilar och andra huvudmaskiner.' },
  { id: 'e_category', label: 'Category', cat: 'entity', desc: 'Kategorier och underkategorier för alla entitetstyper.' },
  { id: 'e_inventorysession', label: 'InventorySession', cat: 'entity', desc: 'Inventeringssessioner med skannade artiklar och manuella antal.' },
  { id: 'e_inventoryreport', label: 'InventoryReport', cat: 'entity', desc: 'Sammanfattningsrapporter från genomförda inventeringar.' },
  { id: 'e_checkoutreport', label: 'CheckoutReport', cat: 'entity', desc: 'Rapporter från utlämning av arbetskläder.' },
  { id: 'e_transfer', label: 'Transfer', cat: 'entity', desc: 'Överföringar av utrustning mellan platser.' },
  { id: 'e_globalconfig', label: 'GlobalAppConfig', cat: 'entity', desc: 'Globala konfigurationer som navigationsordning och dashboard-layout.' },
  { id: 'e_depreciation', label: 'DepreciationSetting', cat: 'entity', desc: 'Avskrivningsinställningar per nivå (Låg/Medel/Hög).' },
  { id: 'e_rolepermission', label: 'RolePermission', cat: 'entity', desc: 'Roll-behörighetsmappning per entitet (CRUD).' },

  // === FUNCTIONS ===
  { id: 'fn_createLoan', label: 'createLoanRequest', cat: 'function', desc: 'Skapar låneförfrågan → skickar email till godkännare + destinationschef + bekräftelse till beställare.' },
  { id: 'fn_approveLoan', label: 'approveLoanRequest', cat: 'function', desc: 'Godkänner/nekar lån → skickar email till alla parter. Stöder delgodkännande och justerat returndatum.' },
  { id: 'fn_returnTools', label: 'returnLoanedTools', cat: 'function', desc: 'Markerar maskiner som returnerade (pending_return) → skickar email till godkännare att bekräfta mottagning.' },
  { id: 'fn_confirmReturn', label: 'confirmReturn', cat: 'function', desc: 'Bekräftar mottagning → skapar ToolLog → uppdaterar verktygsanteckningar → email till alla parter.' },
  { id: 'fn_extendLoan', label: 'extendLoanRequest', cat: 'function', desc: 'Förlänger låneperiod med nytt returndatum.' },
  { id: 'fn_cancelLoan', label: 'cancelLoanRequest', cat: 'function', desc: 'Avbryter låneförfrågan.' },
  { id: 'fn_sendReminder', label: 'sendLoanReminder', cat: 'function', desc: 'Skickar påminnelse-email till alla parter i en låneförfrågan.' },
  { id: 'fn_createWorkwear', label: 'createWorkwearRequest', cat: 'function', desc: 'Skapar arbetskläderbegäran → skickar email till admin_lokalvård + ägare.' },
  { id: 'fn_createLokalvard', label: 'createLokalvardRequest', cat: 'function', desc: 'Skapar lokalvårdsartikelbegäran → skickar email till admins.' },
  { id: 'fn_createUttag', label: 'createUttagFromCheckout', cat: 'function', desc: 'Skapar Uttag-post från godkänd utlämning, beräknar pris per artikel.' },
  { id: 'fn_notifyCheckout', label: 'notifyCheckoutComplete', cat: 'function', desc: 'Skickar email till beställaren att artiklarna är uttagna.' },
  { id: 'fn_logChange', label: 'logToolChange', cat: 'function', desc: 'Registrerar ändringar på ett verktyg i ToolLog.' },
  { id: 'fn_syncUsers', label: 'syncUsersToTeam', cat: 'function', desc: 'Synkar användare till TeamMember-entiteten.' },
  { id: 'fn_syncRoles', label: 'syncTeamMemberRoleToUser', cat: 'function', desc: 'Synkar roller från TeamMember tillbaka till User.' },
  { id: 'fn_exportData', label: 'exportAllData', cat: 'function', desc: 'Exporterar all data i systemet som JSON-fil (ägare).' },
  { id: 'fn_processInkopImport', label: 'processLokalvardInkopImport', cat: 'function', desc: 'Importerar inköp från Excel, matchar artiklar via streckkod/namn.' },
  { id: 'fn_processUttagImport', label: 'processUttagImport', cat: 'function', desc: 'Importerar uttag från Excel-filer.' },
  { id: 'fn_processToolImport', label: 'processToolImport', cat: 'function', desc: 'Importerar maskiner från Excel-filer.' },
  { id: 'fn_deduplicateInkop', label: 'deduplicateInkop', cat: 'function', desc: 'Identifierar och hanterar dubblettor bland inköpsposter.' },
  { id: 'fn_matchUnmatched', label: 'matchUnmatchedInkopByContext', cat: 'function', desc: 'Matchar omatchade inköp mot artiklar via kontext (namn, streckkod).' },
  { id: 'fn_backfillInkop', label: 'backfillMissingInkop', cat: 'function', desc: 'Fyller i saknade inköpsposter baserat på artikeldata.' },
  { id: 'fn_fixInkopIds', label: 'fixImportedInkopArtikelIds', cat: 'function', desc: 'Korrigerar artikel-ID:n på importerade inköp.' },
  { id: 'fn_deduplicateArticles', label: 'deduplicateArticles', cat: 'function', desc: 'Identifierar och slår samman dubblettartiklar.' },
  { id: 'fn_permanentDeleteTrash', label: 'permanentDeleteTrash', cat: 'function', desc: 'Permanent borttagning av mjukraderade poster.' },
  { id: 'fn_createTeamOnUser', label: 'createTeamMemberOnUserCreate', cat: 'function', desc: 'Skapar automatiskt TeamMember när ny användare registreras.' },
  { id: 'fn_setUserRole', label: 'setUserRole', cat: 'function', desc: 'Sätter roll på en användare.' },
  { id: 'fn_deactivateUser', label: 'deactivateUserAndTransferData', cat: 'function', desc: 'Inaktiverar användare och överför data till annan person.' },

  // === ROLES ===
  { id: 'r_lokalvardare', label: 'Lokalvårdare', cat: 'role', desc: 'Kan skapa begäranden för arbetskläder och lokalvårdsartiklar. Kan INTE godkänna.' },
  { id: 'r_admin_lok', label: 'Admin Lokalvård', cat: 'role', desc: 'Kan godkänna begäranden, hantera uttag, streckkoder, lager. Hanterar kunder.' },
  { id: 'r_verktygsfv', label: 'Verktygsförvaltare', cat: 'role', desc: 'Hanterar inventering av maskiner och handredskap. Kan registrera lånförfrågor.' },
  { id: 'r_admin', label: 'Admin', cat: 'role', desc: 'Full systemåtkomst. Hanterar personal, platser och kategorier.' },
  { id: 'r_agare', label: 'Ägare', cat: 'role', desc: 'Tillgång till ALLT: ägaröversikt, rollhantering, avskrivningar, layout-editor, dataexport.' },

  // === EMAILS ===
  { id: 'em_new_loan', label: 'Ny lånförfrågan', cat: 'email', desc: 'Skickas till godkännare, destinationschef + bekräftelse till beställare.' },
  { id: 'em_loan_decision', label: 'Godkänd/Nekad lån', cat: 'email', desc: 'Skickas till beställare, godkännare och destinationschef.' },
  { id: 'em_return_pending', label: 'Retur väntar', cat: 'email', desc: 'Skickas till godkännare (bekräfta mottagning), beställare och destinationschef.' },
  { id: 'em_return_confirmed', label: 'Retur bekräftad', cat: 'email', desc: 'Skickas till låntagare, godkännare, beställare och destinationschef.' },
  { id: 'em_new_workwear', label: 'Ny arbetskläderbegäran', cat: 'email', desc: 'Skickas till alla admin_lokalvård + ägare.' },
  { id: 'em_new_lokalvard', label: 'Ny lokalvårdsbegäran', cat: 'email', desc: 'Skickas till alla admin_lokalvård + ägare.' },
  { id: 'em_checkout_done', label: 'Uttag slutfört', cat: 'email', desc: 'Skickas till beställaren att artiklarna är uttagna.' },
  { id: 'em_reminder', label: 'Påminnelse', cat: 'email', desc: 'Skickas till alla parter i en låneförfrågan.' },

  // === PAGES ===
  { id: 'p_transfers', label: '/Transfers', cat: 'page', desc: 'Lån av utrustning – skapa, godkänna, returnera.' },
  { id: 'p_workwear_req', label: '/ArbetskläderRequestWorkwear', cat: 'page', desc: 'Formulär för att begära arbetskläder.' },
  { id: 'p_workwear_approve', label: '/Arbetsklader/Forfragan', cat: 'page', desc: 'Godkänna arbetskläder-begäranden + scanning + utlämning.' },
  { id: 'p_workwear_checkout', label: '/Arbetsklader/CheckoutReports', cat: 'page', desc: 'Uttagsrapporter för arbetskläder.' },
  { id: 'p_workwear_barcode', label: '/Arbetsklader/Streckkodhantering', cat: 'page', desc: 'Streckkodhantering för arbetskläder.' },
  { id: 'p_lokalvard_req', label: '/LokalvardRequestArtikel', cat: 'page', desc: 'Formulär för att begära lokalvårdsartiklar.' },
  { id: 'p_lokalvard_approve', label: '/Lokalvard/BegaranAttGodkanna', cat: 'page', desc: 'Godkänna lokalvårdsartikelbegäranden.' },
  { id: 'p_lokalvard_uttag', label: '/Lokalvard/NyttUttag', cat: 'page', desc: 'Plocka ut begärda uttag – scanning och kvittering.' },
  { id: 'p_lokalvard_lager', label: '/Lokalvard/Lager', cat: 'page', desc: 'Lagerhantering för lokalvårdsartiklar.' },
  { id: 'p_lokalvard_uttag_list', label: '/Lokalvard/Uttag', cat: 'page', desc: 'Lista över alla uttag.' },
  { id: 'p_lokalvard_kostnad', label: '/Lokalvard/KostnadPerKund', cat: 'page', desc: 'Kostnad per kund och månad.' },
  { id: 'p_lokalvard_kunder', label: '/Lokalvard/Kunder', cat: 'page', desc: 'Kundhantering för lokalvård.' },
  { id: 'p_lokalvard_statistik', label: '/Lokalvard/Produktstatistik', cat: 'page', desc: 'Produktstatistik, förbrukningstrender och beställningslista.' },
  { id: 'p_lokalvard_inkop', label: '/Lokalvard/Inkopshistorik', cat: 'page', desc: 'Inköpshistorik med dubbletthantering.' },
  { id: 'p_lokalvard_omatchade', label: '/Lokalvard/OmatchadeInkop', cat: 'page', desc: 'Omatchade inköp som behöver kopplas till artiklar.' },
  { id: 'p_lokalvard_inkop_import', label: '/Lokalvard/InköpImport', cat: 'page', desc: 'Import av inköpsdata från Excel.' },
  { id: 'p_lokalvard_uttag_import', label: '/Lokalvard/UttagImport', cat: 'page', desc: 'Import av uttagsdata från Excel.' },
  { id: 'p_inventory', label: '/Inventory', cat: 'page', desc: 'Maskinöversikt med alla verktyg.' },
  { id: 'p_handtools', label: '/HandTools', cat: 'page', desc: 'Hantering av handredskap.' },
  { id: 'p_inventorycheck', label: '/InventoryCheck', cat: 'page', desc: 'Inventering av maskiner och handredskap.' },
  { id: 'p_inventoryreports', label: '/InventoryReports', cat: 'page', desc: 'Inventeringsrapporter.' },
  { id: 'p_service', label: '/Service', cat: 'page', desc: 'Servicehantering för maskiner.' },
  { id: 'p_servicemallar', label: '/ServiceMallar', cat: 'page', desc: 'Servicemallar för återkommande åtgärder.' },
  { id: 'p_huvudmaskiner', label: '/Huvudmaskiner', cat: 'page', desc: 'Hantering av huvudmaskiner (traktorer, lastbilar).' },
  { id: 'p_salda', label: '/Inventory/SaldaRedskap', cat: 'page', desc: 'Sålda och kasserade redskap.' },
  { id: 'p_locations', label: '/Locations', cat: 'page', desc: 'Platshantering.' },
  { id: 'p_team', label: '/Team', cat: 'page', desc: 'Personalhantering.' },
  { id: 'p_categories', label: '/Administration/Kategorier', cat: 'page', desc: 'Kategorihantering för alla entitetstyper.' },
  { id: 'p_papperskorg', label: '/Administration/Papperskorg', cat: 'page', desc: 'Papperskorg för mjukraderade poster.' },
  { id: 'p_roller', label: '/Administration/RollBehorigheter', cat: 'page', desc: 'Roller och behörigheter.' },
  { id: 'p_avskrivningar', label: '/Administration/Avskrivningar', cat: 'page', desc: 'Avskrivningsinställningar.' },
  { id: 'p_owner', label: '/OwnerOverview', cat: 'page', desc: 'Ägaröversikt – samlad statistik + dataexport.' },
  { id: 'p_layout_editor', label: '/AdminLayoutEditor', cat: 'page', desc: 'Redigera layout, navigationsordning.' },
  { id: 'p_knowledge', label: '/KnowledgeGraph', cat: 'page', desc: 'Systemarkitektur – Knowledge Graph.' },
  { id: 'p_tool_import', label: '/Inventory/ToolImport', cat: 'page', desc: 'Import av maskiner från Excel.' },
];

export const EDGES = [
  // === LOAN WORKFLOW ===
  { from: 'wf_loan', to: 'fn_createLoan', label: 'startar' },
  { from: 'fn_createLoan', to: 'e_loanrequest', label: 'skapar' },
  { from: 'fn_createLoan', to: 'em_new_loan', label: 'skickar' },
  { from: 'e_loanrequest', to: 'fn_approveLoan', label: 'godkänns/nekas' },
  { from: 'fn_approveLoan', to: 'em_loan_decision', label: 'skickar' },
  { from: 'e_loanrequest', to: 'fn_returnTools', label: 'returneras' },
  { from: 'fn_returnTools', to: 'em_return_pending', label: 'skickar' },
  { from: 'e_loanrequest', to: 'fn_confirmReturn', label: 'bekräftas' },
  { from: 'fn_confirmReturn', to: 'e_toollog', label: 'loggar' },
  { from: 'fn_confirmReturn', to: 'em_return_confirmed', label: 'skickar' },
  { from: 'e_loanrequest', to: 'fn_extendLoan', label: 'förlängs' },
  { from: 'e_loanrequest', to: 'fn_cancelLoan', label: 'avbryts' },
  { from: 'e_loanrequest', to: 'fn_sendReminder', label: 'påminnelse' },
  { from: 'fn_sendReminder', to: 'em_reminder', label: 'skickar' },
  { from: 'e_loanrequest', to: 'e_tool', label: 'refererar till' },
  { from: 'e_loanrequest', to: 'e_location', label: 'destination' },
  { from: 'p_transfers', to: 'wf_loan', label: 'hanterar' },

  // === WORKWEAR WORKFLOW ===
  { from: 'wf_workwear', to: 'fn_createWorkwear', label: 'startar' },
  { from: 'fn_createWorkwear', to: 'e_workwearrequest', label: 'skapar' },
  { from: 'fn_createWorkwear', to: 'em_new_workwear', label: 'skickar' },
  { from: 'e_workwearrequest', to: 'e_checkout', label: 'utlämning' },
  { from: 'e_checkout', to: 'e_arbetsklader', label: 'minskar lager' },
  { from: 'e_checkout', to: 'e_checkoutreport', label: 'genererar rapport' },
  { from: 'p_workwear_req', to: 'wf_workwear', label: 'formulär' },
  { from: 'p_workwear_approve', to: 'e_workwearrequest', label: 'godkänner' },
  { from: 'p_workwear_checkout', to: 'e_checkoutreport', label: 'visar' },

  // === LOKALVÅRD WORKFLOW ===
  { from: 'wf_lokalvard', to: 'fn_createLokalvard', label: 'startar' },
  { from: 'fn_createLokalvard', to: 'e_lokalvardrequest', label: 'skapar' },
  { from: 'fn_createLokalvard', to: 'em_new_lokalvard', label: 'skickar' },
  { from: 'e_lokalvardrequest', to: 'fn_createUttag', label: 'utförs' },
  { from: 'fn_createUttag', to: 'e_uttag', label: 'skapar' },
  { from: 'fn_createUttag', to: 'e_lokalvardsartikel', label: 'minskar lager' },
  { from: 'e_uttag', to: 'e_kund', label: 'kostnad per' },
  { from: 'fn_notifyCheckout', to: 'em_checkout_done', label: 'skickar' },
  { from: 'p_lokalvard_req', to: 'wf_lokalvard', label: 'formulär' },
  { from: 'p_lokalvard_approve', to: 'e_lokalvardrequest', label: 'godkänner' },
  { from: 'p_lokalvard_uttag', to: 'fn_createUttag', label: 'anropar' },
  { from: 'e_inkop', to: 'e_lokalvardsartikel', label: 'tillhör' },
  { from: 'p_lokalvard_lager', to: 'e_lokalvardsartikel', label: 'hanterar' },
  { from: 'p_lokalvard_kostnad', to: 'e_uttag', label: 'visar' },
  { from: 'p_lokalvard_kostnad', to: 'e_kund', label: 'filtrerar per' },
  { from: 'p_lokalvard_kunder', to: 'e_kund', label: 'hanterar' },
  { from: 'p_lokalvard_statistik', to: 'e_lokalvardsartikel', label: 'analyserar' },
  { from: 'p_lokalvard_statistik', to: 'e_inkop', label: 'analyserar' },
  { from: 'p_lokalvard_statistik', to: 'e_uttag', label: 'analyserar' },
  { from: 'p_lokalvard_inkop', to: 'e_inkop', label: 'visar' },
  { from: 'p_lokalvard_omatchade', to: 'fn_matchUnmatched', label: 'anropar' },

  // === IMPORT WORKFLOW ===
  { from: 'wf_import', to: 'fn_processInkopImport', label: 'inköpsimport' },
  { from: 'wf_import', to: 'fn_processUttagImport', label: 'uttagsimport' },
  { from: 'wf_import', to: 'fn_processToolImport', label: 'maskinimport' },
  { from: 'fn_processInkopImport', to: 'e_inkop', label: 'skapar' },
  { from: 'fn_processUttagImport', to: 'e_uttag', label: 'skapar' },
  { from: 'fn_processToolImport', to: 'e_tool', label: 'skapar' },
  { from: 'p_lokalvard_inkop_import', to: 'fn_processInkopImport', label: 'anropar' },
  { from: 'p_lokalvard_uttag_import', to: 'fn_processUttagImport', label: 'anropar' },
  { from: 'p_tool_import', to: 'fn_processToolImport', label: 'anropar' },

  // === INVENTORY WORKFLOW ===
  { from: 'wf_inventering', to: 'e_inventorysession', label: 'skapar session' },
  { from: 'e_inventorysession', to: 'e_inventoryreport', label: 'genererar rapport' },
  { from: 'p_inventorycheck', to: 'wf_inventering', label: 'hanterar' },
  { from: 'p_inventoryreports', to: 'e_inventoryreport', label: 'visar' },
  { from: 'e_inventorysession', to: 'e_tool', label: 'inventerar' },
  { from: 'e_inventorysession', to: 'e_handtool', label: 'inventerar' },

  // === ROLE → PAGE ACCESS ===
  { from: 'r_lokalvardare', to: 'p_workwear_req', label: 'kan använda' },
  { from: 'r_lokalvardare', to: 'p_lokalvard_req', label: 'kan använda' },
  { from: 'r_admin_lok', to: 'p_workwear_approve', label: 'kan använda' },
  { from: 'r_admin_lok', to: 'p_lokalvard_approve', label: 'kan använda' },
  { from: 'r_admin_lok', to: 'p_lokalvard_uttag', label: 'kan använda' },
  { from: 'r_admin_lok', to: 'p_lokalvard_lager', label: 'kan använda' },
  { from: 'r_admin_lok', to: 'p_lokalvard_statistik', label: 'kan använda' },
  { from: 'r_admin_lok', to: 'p_lokalvard_inkop', label: 'kan använda' },
  { from: 'r_admin_lok', to: 'p_lokalvard_kunder', label: 'kan använda' },
  { from: 'r_admin_lok', to: 'p_workwear_barcode', label: 'kan använda' },
  { from: 'r_verktygsfv', to: 'p_transfers', label: 'kan använda' },
  { from: 'r_verktygsfv', to: 'p_inventory', label: 'kan använda' },
  { from: 'r_verktygsfv', to: 'p_inventorycheck', label: 'kan använda' },
  { from: 'r_verktygsfv', to: 'p_handtools', label: 'kan använda' },
  { from: 'r_admin', to: 'p_locations', label: 'kan använda' },
  { from: 'r_admin', to: 'p_team', label: 'kan använda' },
  { from: 'r_admin', to: 'p_categories', label: 'kan använda' },
  { from: 'r_agare', to: 'p_owner', label: 'kan använda' },
  { from: 'r_agare', to: 'p_roller', label: 'kan använda' },
  { from: 'r_agare', to: 'p_avskrivningar', label: 'kan använda' },
  { from: 'r_agare', to: 'p_layout_editor', label: 'kan använda' },

  // === SYNC & LOGGING ===
  { from: 'fn_syncUsers', to: 'e_teammember', label: 'synkar' },
  { from: 'fn_syncRoles', to: 'e_teammember', label: 'synkar' },
  { from: 'fn_logChange', to: 'e_toollog', label: 'skapar' },
  { from: 'fn_exportData', to: 'p_owner', label: 'tillgänglig via' },
  { from: 'fn_createTeamOnUser', to: 'e_teammember', label: 'skapar' },
  { from: 'fn_setUserRole', to: 'e_teammember', label: 'uppdaterar' },
  { from: 'fn_deactivateUser', to: 'e_teammember', label: 'inaktiverar' },
  { from: 'fn_permanentDeleteTrash', to: 'p_papperskorg', label: 'rensar' },

  // === DATA QUALITY ===
  { from: 'fn_deduplicateInkop', to: 'e_inkop', label: 'rensarar' },
  { from: 'fn_matchUnmatched', to: 'e_inkop', label: 'matchar' },
  { from: 'fn_backfillInkop', to: 'e_inkop', label: 'fyller i' },
  { from: 'fn_fixInkopIds', to: 'e_inkop', label: 'korrigerar' },
  { from: 'fn_deduplicateArticles', to: 'e_lokalvardsartikel', label: 'rensar' },

  // === ENTITY RELATIONS ===
  { from: 'e_tool', to: 'e_location', label: 'tillhör' },
  { from: 'e_tool', to: 'e_teammember', label: 'tilldelad' },
  { from: 'e_tool', to: 'e_huvudmaskin', label: 'kopplad till' },
  { from: 'e_tool', to: 'e_servicerecord', label: 'har service' },
  { from: 'e_servicerecord', to: 'e_servicetemplate', label: 'baserad på' },
  { from: 'e_handtool', to: 'e_location', label: 'tillhör' },
  { from: 'e_arbetsklader', to: 'e_location', label: 'tillhör' },
  { from: 'e_teammember', to: 'e_location', label: 'jobbar på' },
  { from: 'e_tool', to: 'e_category', label: 'kategoriserad' },
  { from: 'e_handtool', to: 'e_category', label: 'kategoriserad' },
  { from: 'e_arbetsklader', to: 'e_category', label: 'kategoriserad' },
  { from: 'e_lokalvardsartikel', to: 'e_category', label: 'kategoriserad' },
  { from: 'e_tool', to: 'e_depreciation', label: 'avskrivning' },
  { from: 'e_rolepermission', to: 'e_category', label: 'styr åtkomst' },
  { from: 'p_service', to: 'e_servicerecord', label: 'hanterar' },
  { from: 'p_servicemallar', to: 'e_servicetemplate', label: 'hanterar' },
  { from: 'p_huvudmaskiner', to: 'e_huvudmaskin', label: 'hanterar' },
  { from: 'p_categories', to: 'e_category', label: 'hanterar' },
  { from: 'p_avskrivningar', to: 'e_depreciation', label: 'hanterar' },
  { from: 'p_roller', to: 'e_rolepermission', label: 'hanterar' },
];